# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      SLN_PATH=$(find $APPCENTER_SOURCE_DIRECTORY -iname '*.sln' -type f -print0)
      echo "SLN_PATH = $SLN_PATH"
      
      UWP_PATHS=$(find $APPCENTER_SOURCE_DIRECTORY -iname '*UWP*.csproj' -type f -print0 )
      echo " UWP_PATHS = $UWP_PATHS"
      for p in "$UWP_PATHS"; do
        echo "Removing $p from $SLN_PATH" || true
        dotnet sln $SLN_PATH remove $p || true
      done
      
      ANDROID_PATHS=$(find $APPCENTER_SOURCE_DIRECTORY -iname '*Android*.csproj' -type f -print0 )
      dotnet sln '/Users/runner/work/1/s/VSACDEMO/VSACDEMO.sln' remove '/Users/runner/work/1/s/VSACDEMO/VSACDEMO/VSACDEMO.iOS/VSACDEMO.iOS.csproj'
      echo "ANDROID_PATHS = $ANDROID_PATHS"      
        for p in "$ANDROID_PATHS"; do
            echo "Removing $p from $SLN_PATH" || true
            dotnet sln $SLN_PATH remove $p || true
        done

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
