# Xamarin.Android
trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  system.debug: true

steps:
- task: NuGetToolInstaller@1

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $SLN_PATH = Get-ChildItem -Path '/Users/runner/work/1/s/VSACDEMO' -Include *.sln -recurse
      $AllProjects = Get-ChildItem -Path '/Users/runner/work/1/s/VSACDEMO' -Include *.csproj -Exclude "*Android*.csproj", "VSACDEMO.csproj" -Recurse

      write-host $SLN_PATH
      write-host $AllProjects
      
      foreach ($project in $AllProjects)
      {
          write-host "Removing $project from $SLN_PATH"
          dotnet sln $SLN_PATH remove $project
      }      

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'android_keystore.jks'
    apksignerKeystorePassword: 'Password.1'
    apksignerKeystoreAlias: 'Key0'
    apksignerKeyPassword: 'Password.1'
- task: PublishBuildArtifacts@1
  displayName: Publish build
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)/build
    ArtifactName: build

- task: CmdLine@1
  displayName: Generate UITest tests
  condition: 'and(succeeded(), ne(variables[''Build.Reason''], ''pullRequest''))'
  inputs:
    filename: appcenter
    arguments: >-
      test generate uitest --platform "android" --output-path
      "$(Build.ArtifactStagingDirectory)/GeneratedTest"

- task: NuGetInstaller@0
  displayName: Restore Nuget
  condition: 'and(succeeded(), ne(variables[''Build.Reason''], ''pullRequest''))'
  inputs:
    solution: $(Build.ArtifactStagingDirectory)/GeneratedTest/*.sln
- task: MSBuild@1
  displayName: Build UITest project
  condition: 'and(succeeded(), ne(variables[''Build.Reason''], ''pullRequest''))'
  inputs:
    solution: $(Build.ArtifactStagingDirectory)/GeneratedTest/*.sln
    configuration: Release
    logProjectEvents: true
    createLogFile: true
    msbuildVersion: "14.0"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo $(Build.ArtifactStagingDirectory)
      Get-ChildItem -Path $(Build.ArtifactStagingDirectory) -recurse -depth 2

- task: AppCenterTest@1
  condition: 'and(succeeded(), ne(variables[''Build.Reason''], ''pullRequest''))'
  inputs:
    app: "/Users/runner/work/1/b/Release/com.companyname.vsacdemo.apk"
    artifactsDir: $(Build.ArtifactStagingDirectory)/Artifacts
    framework: uitest
    uitestBuildDir: >-
      '/Users/runner/work/1/a/GeneratedTest/AppCenter.UITest.Android/bin/Release'
      uitestStoreFile: '''
      appSlug: VSAC-DEMOS/DEMO1_Xamarin_Android
      devices: any_top_1_device
      series: launch-tests  
      runOpts: ' -p msft/test-run-origin=Build/Launch'
      showDebugOutput: true
