# Xamarin.Android
trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  system.debug: true


steps:
- task: NuGetToolInstaller@1

- task: PowerShell@2
  displayName: Remove Unnecessary Projects
  inputs:
    targetType: 'inline'
    script: |
      $SLN_PATH = Get-ChildItem -Path '/Users/runner/work/1/s/VSACDEMO' -Include *.sln -recurse
      $AllProjects = Get-ChildItem -Path '/Users/runner/work/1/s/VSACDEMO' -Include *.csproj -Exclude "*Android*.csproj", "VSACDEMO.csproj" -Recurse

      write-host $SLN_PATH
      write-host $AllProjects
      
      foreach ($project in $AllProjects)
      {
          write-host "Removing $project from $SLN_PATH"
          dotnet sln $SLN_PATH remove $project
      }      
      write-host (${KeystorePassword}).Length
      write-host (${KeystoreAlias}).Length
      write-host (${KeyPassword}).Length
      $vars = ([System.Environment]::GetEnvironmentVariables())
      write-host $vars 

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: DownloadSecureFile@1
  inputs:
    secureFile: android_keystore.jks
    
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'android_keystore.jks'
    apksignerKeystorePassword: $(KeystorePassword)
    apksignerKeystoreAlias: $(KeystoreAlias)
    apksignerKeyPassword: $(KeyPassword)
- task: PublishBuildArtifacts@1
  displayName: Publish build
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)/build
    ArtifactName: build